version: '3.9'
services:
  app:
    image: ${APP_IMAGE:?}
    ports:
      - "${HOST_PORT:?}:${CONTAINER_PORT:?}"
    environment:
      SENTRY_DSN: ${SENTRY_DSN:?}
      SERVER_ADDRESS: ${SERVER_ADDRESS:?}
      AUTH_USER: ${AUTH_USER:?}
      AUTH_PASS: ${AUTH_PASS:?}
      APP_IMAGE: ${APP_IMAGE:?}
      HOST_PORT: ${HOST_PORT:?}
      CONTAINER_PORT: ${CONTAINER_PORT:?}
      SQLITE_DB_PATH: ${SQLITE_DB_PATH:?}
      DOMAIN: ${DOMAIN:?}
      SECRET: ${SECRET:?}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID:?}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET:?}
      OPENAI_API_KEY: ${OPENAI_API_KEY:?}
      CHAT_GPT_SYSTEM_MESSAGE: ${CHAT_GPT_SYSTEM_MESSAGE:?}
      CHAT_GPT_MODEL: ${CHAT_GPT_MODEL:?}